[package]
name = "rs-conllu"
description = "A parser for the CoNLL-U format of the Universal Dependencies project."
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.40"
